
# GET ALL SETUPS USER HAS
GET https://{{host}}/setups
Authorization: Bearer {{token}}
###

# CREATE SETUP
POST https://{{host}}/setups
Authorization: Bearer {{token}}
Content-Type: application/json

{   
  "cpuId": "5936138d-2118-4425-a199-d57d587382ee",
  "ramId": "8d865fee-f704-490a-81a1-bc82a81fe12b",
  "romId": "74e656d7-5b28-4d63-b335-0caf9833b2a6",
  "ipId": "9b5ee8c4-bb5c-4181-8fb9-f05f5087b2fd",
  "osId": "f5306e60-4c52-4579-8d4e-0eb350be4433"
}
###

# UPDATE SETUP
PUT https://{{host}}/setups
Authorization: Bearer {{token}}
Content-Type: application/json

{   
  "setupId": "6166c35a-e449-46a6-90ab-a57b1c4eba71", 
  "cpuId": "5936138d-2118-4425-a199-d57d587382ee",
  "ramId": "8d865fee-f704-490a-81a1-bc82a81fe12b",
  "romId": "74e656d7-5b28-4d63-b335-0caf9833b2a6",
  "ipId": "9b5ee8c4-bb5c-4181-8fb9-f05f5087b2fd",
  "osId": "f5306e60-4c52-4579-8d4e-0eb350be4433"
}
#### "setupId": "..." -> required
#### "cpuId": "..." -> optional
#### "ramId": "..." -> optional
#### "romId": "..." -> optional
#### "ipId": "..." -> optional
#### "osId": "..." -> optional
###

# RUN SETUP
PUT https://{{host}}/setups/run
Authorization: Bearer {{token}}
Content-Type: application/json

{   
  "setupId": "6166c35a-e449-46a6-90ab-a57b1c4eba71"
}
###

# STOP SETUP
PUT https://{{host}}/setups/stop
Authorization: Bearer {{token}}
Content-Type: application/json

{   
  "setupId": "6166c35a-e449-46a6-90ab-a57b1c4eba71"
}
###

# GET BY ID SETUP
GET https://{{host}}/setups/6166c35a-e449-46a6-90ab-a57b1c4eba71
Authorization: Bearer {{token}}
###

# REMOVE SETUP
DELETE https://{{host}}/setups
Authorization: Bearer {{token}}
Content-Type: application/json

{   
  "setupId": "4792becb-1b20-49e6-890f-442988206b40"
}
###