services:
  remote-cleaner-database:
    image: postgres
    container_name: remote-cleaner-database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume:
