// <auto-generated />
using DataAccessLayer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DataAccessLayer.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Beta"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project Delta"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Project", b =>
                {
                    b.OwnsMany("DataAccessLayer.Entities.Model", "Models", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("model_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.Property<int>("ProjectId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("project_id");

                            b1.HasKey("Id")
                                .HasName("pk_models");

                            b1.HasIndex("ProjectId")
                                .HasDatabaseName("ix_models_project_id");

                            b1.ToTable("models", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_models_projects_project_id");

                            b1.OwnsMany("DataAccessLayer.Entities.Texture", "Textures", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("texture_id");

                                    b2.Property<string>("Color")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("color");

                                    b2.Property<int>("ModelId")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("model_id");

                                    b2.Property<string>("Pattern")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("pattern");

                                    b2.HasKey("Id")
                                        .HasName("pk_textures");

                                    b2.HasIndex("ModelId")
                                        .HasDatabaseName("ix_textures_model_id");

                                    b2.ToTable("textures", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ModelId")
                                        .HasConstraintName("fk_textures_models_model_id");

                                    b2.HasData(
                                        new
                                        {
                                            Id = 1,
                                            Color = "Black",
                                            ModelId = 1,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 2,
                                            Color = "Red",
                                            ModelId = 1,
                                            Pattern = "Stripes"
                                        },
                                        new
                                        {
                                            Id = 3,
                                            Color = "White",
                                            ModelId = 2,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 4,
                                            Color = "Blue",
                                            ModelId = 3,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 5,
                                            Color = "Yellow",
                                            ModelId = 4,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 6,
                                            Color = "Green",
                                            ModelId = 4,
                                            Pattern = "Stripes"
                                        },
                                        new
                                        {
                                            Id = 7,
                                            Color = "Black",
                                            ModelId = 5,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 8,
                                            Color = "White",
                                            ModelId = 6,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 9,
                                            Color = "Red",
                                            ModelId = 7,
                                            Pattern = "Solid"
                                        },
                                        new
                                        {
                                            Id = 10,
                                            Color = "Blue",
                                            ModelId = 8,
                                            Pattern = "Solid"
                                        });
                                });

                            b1.Navigation("Textures");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Name = "Box",
                                    ProjectId = 1
                                },
                                new
                                {
                                    Id = 2,
                                    Name = "Sphere",
                                    ProjectId = 1
                                },
                                new
                                {
                                    Id = 3,
                                    Name = "Cylinder",
                                    ProjectId = 1
                                },
                                new
                                {
                                    Id = 4,
                                    Name = "Cylinder1",
                                    ProjectId = 2
                                },
                                new
                                {
                                    Id = 5,
                                    Name = "Cylinder2",
                                    ProjectId = 2
                                },
                                new
                                {
                                    Id = 6,
                                    Name = "Sphere",
                                    ProjectId = 2
                                },
                                new
                                {
                                    Id = 7,
                                    Name = "Box1",
                                    ProjectId = 3
                                },
                                new
                                {
                                    Id = 8,
                                    Name = "Box2",
                                    ProjectId = 3
                                });
                        });

                    b.OwnsMany("DataAccessLayer.Entities.Setting", "Settings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("setting_id");

                            b1.Property<string>("Parameter")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("parameter");

                            b1.Property<int>("ProjectId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("project_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_settings");

                            b1.HasIndex("ProjectId")
                                .HasDatabaseName("ix_settings_project_id");

                            b1.ToTable("settings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_settings_projects_project_id");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Parameter = "Resolution",
                                    ProjectId = 1,
                                    Value = "FullHd"
                                },
                                new
                                {
                                    Id = 2,
                                    Parameter = "Environment",
                                    ProjectId = 1,
                                    Value = "DevelopMode"
                                },
                                new
                                {
                                    Id = 3,
                                    Parameter = "Resolution",
                                    ProjectId = 2,
                                    Value = "2K"
                                },
                                new
                                {
                                    Id = 4,
                                    Parameter = "Resolution",
                                    ProjectId = 3,
                                    Value = "1080"
                                },
                                new
                                {
                                    Id = 5,
                                    Parameter = "Environment",
                                    ProjectId = 3,
                                    Value = "Production"
                                });
                        });

                    b.Navigation("Models");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
